server:
  port: 8000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_database
    username: postgres
    password: san

  sql:
    init:
      mode: always
      platform: postgresql

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        #        show_sql: true
      #        format_sql: true
    show-sql: true
    generate-ddl: true

jwt:
  header : Authoization
  secret : 
  token-validity-in-seconds: 86400
